## makeCacheMatrix: generate a special matrix for cached inverse
## cacheSolve: provide a cached matrix solve version

## makeCacheMatrix creates a special "matrix", 
## Input: a matrix
## Return: a special matrix, actually a list, including following elements:
##    set the value of the internal matrix
##    get the value of the internal matrix
##    set the value of the inverse matrix
##    get the value of the inverse matrix
makeCacheMatrix <- function(x = matrix()) {
    inv <- NULL
    set <- function(y){
        x <<- y
        m <<- NULL
    }
    get <- function() x
    setinverse <- function(inverse) inv <<- inverse
    getinverse <- function() inv
    ## return the special matrix, a four items list
    list(set = set, get = get, setinverse = setinverse, getinverse = getinverse)
}


## cacheSolve calculates the inverse of the special "matrix" created with the above function. 
## Input: a special matrix which is generated by function makeCacheMatrix
## Return: the inverse matrix
## Details:
##        The function first checks to see if the inverse matrix has already been calculated. 
##        If so, it gets the inverse matrix from the cache and skips the computation. 
##        Otherwise, it calculates the inverse matrix and set it back via setinverse function.
cacheSolve <- function(x, ...) {
    ## Return a matrix that is the inverse of 'x'
    inv <- x$getinverse()
    ## Check if the cached inverse is NULL
    if(!is.null(inv)){
        message("getting cached inverse matrix")
    }
    else{
        ## Fetch original matrix and calc the inverse
        m <- x$get()
        inv <- solve(m, ...)
        ## set the inverse back
        x$setinverse(inv)
    }
    inv    
}
